[package]
name = "lotta-extensions"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
lotta-runtime = { version = "0.1.0", path = "../lotta-runtime" }
lotta-tools = { version = "0.1.0", path = "../lotta-tools", default-features = false }
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
lotta-domain = { version = "0.1.0", path = "../lotta-domain" }
lotta-memfs = { version = "0.1.0", path = "../lotta-memfs" }
serde_json.workspace = true

[lints]
workspace = true
