[package]
name = "lotta-store"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
lotta-domain = { version = "0.1.0", path = "../lotta-domain" }
lotta-runtime = { version = "0.1.0", path = "../lotta-runtime" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
lotta-testkit = { version = "0.1.0", path = "../lotta-testkit" }
tracing-subscriber.workspace = true
