[package]
name = "lotta-testkit"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
lotta-domain = { version = "0.1.0", path = "../lotta-domain" }
lotta-runtime = { version = "0.1.0", path = "../lotta-runtime" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt"] }
tokio-util.workspace = true
uuid.workspace = true

[dev-dependencies]
proc-macro2 = { version = "1.0.101", features = ["span-locations"] }
quote = "1.0.40"
syn = { version = "2.0.106", features = ["full", "visit"] }
toml = "0.9.5"

[lints]
workspace = true
